### ISSUE TITLE
Token formatting issue

### ISSUE THREAD

**Issue by maravone** [April-Gras/obsidian-auto-timelines#62] opened 2023-08-15 03:45 UTC
Perhaps I'm doing something wrong, or perceiving the capabilities of the plugin incorrectly, but as far as I can tell, thats not the case.
As I try to format the date tokens, everytime I change one of the tokens from numerical to string, or change the numerical minimal length, every other token gets reset. As it stands, it seems I can only configure one date. The same issue happens in Advanced Mode as it asks me to update

Currently trying to establish a simple era-year-month-day. Where ideally it would end up displaying as "Era Name"(as string): "day"(number) "Month"(string) "Year"(number) where minimal number would be 1.

**Comment by April-Gras** [comment] 2023-08-15 11:45
Hey @maravone, thank you for taking the time to report this
Do you have any more details ?
A screen recording of you going trough the settings and trying to get it to work would be perfect. I can't reproduce the token configurations resseting myself, so I'm quite curious as too how it goes down for you.

>  or perceiving the capabilities of the plugin incorrectl
No you're all good, the plugin should be able to be configured in the way you're trying to. with a little bit more info on what exactly is happening I'm sure I could help you

**Comment by maravone** [comment] 2023-08-15 12:53
Of course, here you go:
![obsidian_calendar](https://github.com/April-Gras/obsidian-auto-timelines/assets/70380183/e2a4760d-7dc6-4abe-b259-1e113f43a494)

In the meantime, I was able to circumvent the issue by just configuring everything through the Advanced mode menu, defining each token in time, closing the menu, opening it again for each time.

**Comment by April-Gras** [comment] 2023-09-07 21:57
Hey @maravone I believe this was fixed in a subsequent release, not sure when but: I tried to reproduce this and just could not
If you still have this issue I'll reopen this ticket

**Closed by April-Gras** 2023-09-07 21:57 UTC
Labels: bug, question
